# Mehr Speicher für Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric-Versionen, prüfen auf https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_api_version=0.161.0+26.2

# Mod
mod_version=1.0.1
maven_group=io.github.jan1a234
archives_base_name=goblinforest

# Tests
junit_version=5.12.2
